<?php
return [
    [
        'username' => 'erau',
        'auth_key' => 'tUu1qHcde0diwUol3xeI-18MuHkkprQI',
        // password_0
        'password_hash' => '$2y$13$nJ1WDlBaGcbCdbNC5.5l4.sgy.OMEKCqtDQOdQ2OWpgiKRWYyzzne',
        'password_reset_token' => 'RkD_Jw0_8HEedzLk7MM-ZKEFfYR7VbMr_1392559490',
        'created_at' => '1392559490',
        'updated_at' => '1392559490',
        'email' => 'sfriesen@jenkins.info',
        'rest_token' => 'uf0OYTWi6BdBG7COVH7g4-opwJwQAN2V',
        'rest_token_expired_at' => date("Y-m-d",time()+24*3600),
    ],
    [
        'username' => 'test.test',
        'auth_key' => 'O87GkY3_UfmMHYkyezZ7QLfmkKNsllzT',
        // Test1234
        'password_hash' => 'O87GkY3_UfmMHYkyezZ7QLfmkKNsllzT',
        'email' => 'test@mail.com',
        'status' => '9',
        'created_at' => '1548675330',
        'updated_at' => '1548675330',
        'verification_token' => '4ch0qbfhvWwkcuWqjN8SWRq72SOw1KYT_1548675330',
        'rest_token' => 'RsTfu4TRv1sFabH1PRzFbNg2dmwPi4W_',
        'rest_token_expired_at' => date("Y-m-d",time()-24*3600),
    ],
    [
        'username'=>'user1',
        'auth_key'=> Yii::$app->security->generateRandomString(),
        'password_hash'=> Yii::$app->security->generatePasswordHash('123'),
        'email'=>'user1@mail.com',
        'status'=>10,
        'created_at'=>time(),
        'updated_at'=>time(),
        'rest_token' => Yii::$app->security->generateRandomString(),
        'rest_token_expired_at' => date("Y-m-d",time()+24*3600),
    ],
    [
        'username'=>'user2',
        'auth_key'=> Yii::$app->security->generateRandomString(),
        'password_hash'=> Yii::$app->security->generatePasswordHash('123'),
        'email'=>'user2@mail.com',
        'status'=>10,
        'created_at'=>time(),
        'updated_at'=>time(),
        'rest_token' => Yii::$app->security->generateRandomString(),
        'rest_token_expired_at' => date("Y-m-d",time()+24*3600),
    ],
    [
        'username'=>'user3',
        'auth_key'=> Yii::$app->security->generateRandomString(),
        'password_hash'=> Yii::$app->security->generatePasswordHash('123'),
        'email'=>'user3@mail.com',
        'status'=>10,
        'created_at'=>time(),
        'updated_at'=>time(),
        'rest_token' => Yii::$app->security->generateRandomString(),
        'rest_token_expired_at' => date("Y-m-d",time()+24*3600),
    ],
];
